@baseurl = http://localhost:3000

# Recados
GET {{baseurl}}/recados/
# ?limit=10
# &offset=0
###
GET {{baseurl}}/recados/4


###
POST  {{baseurl}}/recados
Content-Type: application/json

{
    "texto": "Recado de teste",	
    "de": "caua",
    "para": "Teste",
    "lido": true
}

### Atualizar um recado

PUT {{baseurl}}/recados/3
Content-Type: application/json

{
  "titulo": "Recado atualizado",
  "descricao": "Descrição do recado atualizado",
  "data": "2023-10-02T00:00:00.000Z",
  "hora": "14:00:00"
}

###
DELETE {{baseurl}}/recados/1
