@baseurl = http://localhost:3000

# Recados
GET {{baseurl}}/recados/
# ?limit=10
# &offset=0
###
GET {{baseurl}}/recados/1
###
POST  {{baseurl}}/recados

Content-Type: application/json
{
    "texto": "Novo Recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
}

### Atualizar um recado

PUT {{baseurl}}/recados/1

Content-Type: application/json
{
  "titulo": "Recado atualizado",
  "descricao": "Descrição do recado atualizado",
  "data": "2023-10-02T00:00:00.000Z",
  "hora": "14:00:00"
}

###
DELETE {{baseurl}}/recados/1
